version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  
    networks:
      - my-network
    container_name: primeapp-frontend

networks:
  my-network:
    driver: bridge
